# Prototype paths
set(WARPSDK_EXE_SUFX ".exe")
set(WARPSDK_WABT_ROOT "c:/prog/wabt")
set(WARPSDK_LLVM_ROOT "c:/prog/llvm80/bin")

set(WARPSDK_WASM2C "${WARPSDK_WABT_ROOT}/wasm2c${WARPSDK_EXE_SUFX}")
set(WARPSDK_AR "${WARPSDK_LLVM_ROOT}/llvm-ar${WARPSDK_EXE_SUFX}")
set(WARPSDK_CLANG "${WARPSDK_LLVM_ROOT}/clang${WARPSDK_EXE_SUFX}")
set(WARPSDK_LINKER "${WARPSDK_LLVM_ROOT}/wasm-ld${WARPSDK_EXE_SUFX}")

